name: General Meeting Reminder

on:
# General scheduler
  schedule:
    # cron uses UTC so make sure you -5 hours, use this: https://crontab.cronhub.io to help.
    # 1 day in advance of general meeting (Monday at 12:00 PM EST) - Every other Monday 
    - cron: '0 17 */14 * 1'
    # Day of general meeting (Tuesday at 12:00 PM EST) - Every other Tuesday
    - cron: '0 17 */14 * 2'
# Controls scheduler
  schedule:
    # 1 day in advance of control meeting (Friday at 12:00 PM EST) - Every Friday
    - cron: '0 17 * * 5'
    # Day of control meeting (Saturday at 12:00 PM EST) - Every Saturday
    - cron: '0 17 * * 6'

# Server Role IDs
# Software Team: 1203519324304838717
# Mechanical Team: 1203520461342900276
# Electrical Team: 1203520031980527626
# Outreach Team: 1095433102525989014
# Website/Video Team: 1339713244952137829

jobs:
  send-general-meetings-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Reminder General Meeting
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "@everyone : General Meeting tomorrow from 6:30 PM to 8:00 PM at FCAE 040! Don’t miss it!"}' \
               ${{ secrets.ORG_DISCORD_WEBHOOK_URL }}
      - name: Send Discord Reminder Day Of General Meeting
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "@everyone : General Meeting today from 6:30 PM to 8:00 PM at FCAE 040! Don’t miss it!"}' \
               ${{ secrets.ORG_DISCORD_WEBHOOK_URL }}
  send-controls-meeting-reminder:
      runs-on: ubuntu-latest
      steps:
        - name: Send Controls Meeting Reminder
          run: |
            curl -H "Content-Type: application/json" \
                -X POST \
                -d '{"content": "<@&1203519324304838717> : Controls Meeting tomorrow at 6:00 PM  Don’t miss it!"}' \
                ${{ secrets.ORG_DISCORD_WEBHOOK_URL }}
        - name: Send Controls Meeting Reminder Day Of
          run: |
            curl -H "Content-Type: application/json" \
                -X POST \
                -d '{"content": "<@&1203519324304838717> : Controls Meeting today at 6:00 PM. Don’t miss it!"}' \
                ${{ secrets.ORG_DISCORD_WEBHOOK_URL }}