name: General Meeting Reminder

on:
  schedule:
    # 1 day in advance (Monday at 12:00 PM EST / 5:00 PM UTC) - Every other Monday
    - cron: '0 17 */14 * 1'
    # Day of event (Tuesday at 12:00 PM EST / 5:00 PM UTC) - Every other Tuesday
    - cron: '0 17 */14 * 2'

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Reminder
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "@everyone, General Meeting tomorrow from 6:30 PM to 8:00 PM at FCAE 040! Don’t miss it!"}' \
               ${{ secrets.ORG_DISCORD_WEBHOOK_URL }}

  send-reminder-day-of:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Reminder Day Of
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "everyone, General Meeting today from 6:30 PM to 8:00 PM at FCAE 040! Don’t miss it!"}' \
               ${{ secrets.ORG_DISCORD_WEBHOOK_URL }}