name: Test Discord Notifier

on: 
  schedule:
  - cron: '56 3 * * *'
  
jobs:
  send-general-meetings-reminder:
    runs-on: ubuntu-latest
    steps:
    - name: Send Discord Reminder General Meeting
      run: | 
        curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "<@&1019044529527066664> This is a scheduled notification test."}' \
          ${{ secrets.ORG_DISCORD_WEBHOOK_URL }}
